services:
    _defaults:
        autowire: true
        autoconfigure: true

    # AjaxReload
    Codefog\HasteBundle\AjaxReloadManager: ~
    Codefog\HasteBundle\EventListener\AjaxReloadListener: ~

    # DcaAjaxOperations
    Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener: ~

    # DcaDateRangeFilter
    Codefog\HasteBundle\EventListener\DcaDateRangeFilter: ~

    # Relations
    Codefog\HasteBundle\Model\Relations:
        public: true
