services:
    _defaults:
        autowire: true
        autoconfigure: true

    # AjaxReload
    Codefog\HasteBundle\AjaxReloadManager: ~
    Codefog\HasteBundle\EventListener\AjaxReloadListener: ~

    # DcaAjaxOperations
    Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener: ~

    # DcaDateRangeFilter
    Codefog\HasteBundle\EventListener\DcaDateRangeFilter: ~

    # Formatter
    Codefog\HasteBundle\Formatter: ~

    # Relations
    Codefog\HasteBundle\EventListener\DcaRelationsListener: ~
    Codefog\HasteBundle\DcaRelationsManager:
        public: true

    # StringParser
    Codefog\HasteBundle\StringParser: ~

    # UndoManager
    Codefog\HasteBundle\UndoManager: ~

    # UrlParser
    Codefog\HasteBundle\UrlParser: ~
