services:
    _defaults:
        autowire: true
        autoconfigure: true

    # AjaxReload
    Codefog\HasteBundle\AjaxReloadManager: ~
    Codefog\HasteBundle\EventListener\AjaxReloadListener: ~

    # DcaAjaxOperations
    Codefog\HasteBundle\EventListener\DcaAjaxOperationsListener: ~
